name = "NAJ"
uuid = "3a8672d3-a8d7-4fb7-80dc-526698d5a642"
authors = ["julia-KAERI <julia.kaeri@gmail.com>"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
